language: ruby
cache: bundler
services: postgresql
bundler_args: --without production
rvm:
  - 2.3.0
  - jruby
  - 2.0.0-p247
  
  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec /test
